### ISSUE TITLE
how to initialize v0

### ISSUE THREAD

**Issue by chenhehong** [intersun/LightningDOT#1]
Hello，I want to know how to initialize the weight of the special image [CLS] embedding v0? where is the corresponding code file?

**Comment by intersun** [comment]
could you please be more specific? Sorry that I didn't quite get your question. The model is initialized by BERT or UNITER, hence the the embedding of [CLS] simply is the output of first token from the last layer

**Comment by chenhehong** [comment]
how to initialize the weight of v0(corresponding to the the red box from the paper's screenshots)
![image](https://user-images.githubusercontent.com/6380063/114992912-d8570d00-9ecd-11eb-9fed-df8f8d3b014b.png)

**Comment by intersun** [comment]
"embedding of [CLS] simply is the output of first token from the last layer", the model is initialized by BERT or UNITER

**Comment by chenhehong** [comment]
Got it, thx
