### ISSUE TITLE
pretrained weights are no longer avaliable.

### ISSUE THREAD

**Issue by wxywb** [intersun/LightningDOT#10]
Hello, 
I tried test the model, however I found the link is no longer avaliable.
<img width="1260" alt="截屏2022-11-14 下午2 51 06" src="https://user-images.githubusercontent.com/5432721/201593930-7925d418-c947-442b-8ccf-f014f5de5b12.png">

**Comment by intersun** [comment]
I cannot access the internal resource anymore, @ChenRocks  Could you please help to double-check with the link? Thanks!

**Comment by ChenRocks** [comment]
#11 should fix it
