### ISSUE TITLE
datasets missing

### ISSUE THREAD

**Issue by dahrs** [intersun/LightningDOT#2]
Hi!
I  see in the config file that it's expecting multiple train and val datasets (ending in ".db"). 
Could you tell me where can I download them or what does the data look like (is it one per line, tab separated?)
Thanks in advance,
David

**Comment by ChenRocks** [comment]
I will upload a download script for the data in the next couple of days. Please stay tuned, thanks!

**Comment by dahrs** [comment]
Thanks, that would be great!

**Comment by dahrs** [comment]
Any news on when will it be available?
Thanks in advance.

**Comment by intersun** [comment]
We have uploaded COCO and Flickr dataset to the link below, please let us know if you still have any questions. 

We will modify the download script and demo ipython notebook later.

Thanks!


https://acvrpublicycchen.blob.core.windows.net/uniter/img_db/coco_train2014.tar
https://acvrpublicycchen.blob.core.windows.net/uniter/img_db/coco_val2014.tar
https://acvrpublicycchen.blob.core.windows.net/uniter/txt_db/itm_coco_train.db.tar
https://acvrpublicycchen.blob.core.windows.net/uniter/txt_db/itm_coco_restval.db.tar
https://acvrpublicycchen.blob.core.windows.net/uniter/txt_db/itm_coco_val.db.tar
https://acvrpublicycchen.blob.core.windows.net/uniter/txt_db/itm_coco_test.db.tar

https://acvrpublicycchen.blob.core.windows.net/uniter/img_db/flickr30k.tar
https://acvrpublicycchen.blob.core.windows.net/uniter/txt_db/itm_flickr30k_train.db.tar
https://acvrpublicycchen.blob.core.windows.net/uniter/txt_db/itm_flickr30k_val.db.tar
https://acvrpublicycchen.blob.core.windows.net/uniter/txt_db/itm_flickr30k_test.db.tar

**Comment by mojivalipour** [comment]
Hey, @intersun, thanks for sharing datasets. Would you please also consider sharing CC and SBU datasets as well? So we can use your pretraining dataset and reproduce the results.
